# Site settings
title: "4thwave Ventures"
email: "ted@4thwaveventures.com"
description: "4thwave is a intername software company" 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: "portalco"
github_username: portalco

# Build settings
markdown: kramdown
